version: '3'
services:
  traefik:
    image: traefik
    container_name: traefik
    restart: always
    command:
      - "--log.level=WARN"
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
      - "--api.insecure=true"
      - "--providers.file.filename=/traefik-dynamic.toml"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.acmehttpchallenge.acme.httpchallenge=true"
      - "--certificatesResolvers.acmehttpchallenge.acme.httpChallenge.entryPoint=web"
      - "--certificatesresolvers.acmehttpchallenge.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.acmehttpchallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - "~/letsencrypt:/letsencrypt"
      - "./traefik-dynamic.toml:/traefik-dynamic.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  distvisor:
    image: ${DOCKER_IMG}:${CURRENT_VERSION}
    container_name: distvisor
    restart: always
    volumes: 
      - "./data:/app/Data"
      - "./.env:/app/config.env"
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.redirecthttps.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirecthttps.redirectscheme.permanent=true"
      - "traefik.http.routers.distvisor_insecure.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.distvisor_insecure.entrypoints=web"
      - "traefik.http.routers.distvisor_insecure.middlewares=https-only@file"
      - "traefik.http.routers.distvisor.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.distvisor.entrypoints=websecure"
      - "traefik.http.routers.distvisor.tls.certresolver=acmehttpchallenge"
      - "traefik.http.routers.distvisor.middlewares=default"
      - "traefik.http.middlewares.default.chain.middlewares=https-only@file,security-headers@file,compress-all@file"