[tls.options]
  [tls.options.default]
    minVersion = "VersionTLS12"
    cipherSuites = [
        "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
        "TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384",
        "TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305",
        "TLS_AES_128_GCM_SHA256",
        "TLS_AES_256_GCM_SHA384",
        "TLS_CHACHA20_POLY1305_SHA256"
    ]
    sniStrict = true

[http.middlewares]
  [http.middlewares.compress-all.compress]

  [http.middlewares.https-only.redirectScheme]
    scheme = "https"
    permanent = true

  [http.middlewares.security-headers.headers]
    BrowserXssFilter = true
    ContentSecurityPolicy = "default-src 'none'; img-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; manifest-src 'self'; font-src 'self'"
    ContentTypeNosniff = true
    ForceSTSHeader = true
    FrameDeny = true
    SSLRedirect = true
    STSIncludeSubdomains = true
    STSPreload = true
    STSSeconds = 315360000