name: Distvisor.Web release

on:
  release:
    types: [published]
    
jobs:
  build_release_amd64:
    name: Build release-amd64
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: dotnet publish
      working-directory: src
      run: dotnet publish -c Release -o ../deploy/amd64/out /p:Version=${GITHUB_REF#refs/tags/} Distvisor.Web

    - name: Create and push docker image
      working-directory: deploy/amd64
      run: |
        docker build -t ${{ secrets.DOCKER_IMG_NAME }}:${GITHUB_REF#refs/tags/} -t ${{ secrets.DOCKER_IMG_NAME }}:latest .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_IMG_NAME }}:${GITHUB_REF#refs/tags/}
        docker push ${{ secrets.DOCKER_IMG_NAME }}:latest
     
  build_release_arm32v7:
    name: Build release-arm32v7
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301

    - name: dotnet publish
      working-directory: src
      run: dotnet publish -c Release -o ../deploy/arm32v7/out -r linux-arm /p:Version=${GITHUB_REF#refs/tags/} Distvisor.Web

    - name: Create and push docker image
      working-directory: deploy/arm32v7
      run: |
        docker build -t ${{ secrets.DOCKER_IMG_NAME }}:${GITHUB_REF#refs/tags/}-arm32v7 .
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ${{ secrets.DOCKER_IMG_NAME }}:${GITHUB_REF#refs/tags/}-arm32v7
