name: Distvisor.Web deploy
on: repository_dispatch
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v1
      
    - name: Create /tmp/config.ovpn
      run: |
        echo "${{ secrets.CONFIG_OVPN }}" >> /tmp/config.ovpn
        sudo chmod 600 /tmp/config.ovpn
        
    - name: Create /tmp/auth.txt
      run: |
        echo "${{ secrets.AUTH_OVPN }}" >> /tmp/auth.txt
        sudo chmod 600 /tmp/auth.txt
    
    - name: Install Open VPN
      run: sudo apt-get install openvpn
        
    - name: Connect Open VPN
      run: sudo openvpn --config /tmp/config.ovpn --daemon
      
    - name: Ping Server
      run: sudo ping -c10 -W15 ${{ secrets.SERVER_LOCAL_IP }}
  
    - name: SCP deploy catalog
      uses: appleboy/scp-action@v0.0.4
      with:
        host: ${{ secrets.SERVER_LOCAL_IP }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        source: "deploy/*.*"
        target: "test"
  
    - name: Kill Open VPN
      if: always()
      run: sudo killall openvpn
