name: Distvisor.Web deploy
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Deploy or Redeploy'
        required: true
        default: 'Redeploy'
      environment:
        description: 'Environment'
        required: true
        default: 'Preview'
      version:
        description: 'App version'
        required: false
        default: 'latest'
  push:
    branches: [ master ]
    
jobs:
  deploy_preview_arm32v7:
    name: Deploy preview-arm32v7
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v1
      
    - name: Create config.ovpn
      run: |
        echo "${{ secrets.CONFIG_OVPN }}" >> config.ovpn
        sudo chmod 600 config.ovpn
    
    - name: Create auth.txt
      run: |
        echo "${{ secrets.AUTH_OVPN }}" >> auth.txt
        sudo chmod 600 auth.txt
    
    - name: Install Open VPN
      run: sudo apt-get install openvpn
        
    - name: Connect Open VPN
      run: sudo openvpn --config config.ovpn --daemon
      
    - name: Ping Server
      run: sudo ping -c10 -W15 ${{ secrets.SERVER_LOCAL_IP }}
      
    - name: Kill Open VPN
      if: always()
      run: sudo killall openvpn
