name: Distvisor.Web deploy
on: repository_dispatch
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:    
    - name: Create /tmp/config.ovpn
      run: |
        echo "${{ secrets.CONFIG_OVPN }}" >> /tmp/config.ovpn
        sudo chmod 600 /tmp/config.ovpn
        
    - name: Create /tmp/auth.txt
      run: |
        echo "${{ secrets.AUTH_OVPN }}" >> /tmp/auth.txt
        sudo chmod 600 /tmp/auth.txt
    
    - name: Install Open VPN
      run: sudo apt-get install openvpn
        
    - name: Connect OpenVpn
      run: sudo openvpn --config /tmp/config.ovpn
  
    - name: Kill OpenVpn
      if: always()
      run: sudo killall openvpn
