name: Distvisor build

on: [push]

jobs:
  build_angular:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Install packages
      run: npm install
    - name: Build Angular
      run: npm run build --if-present
    

  build_aspnet:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
