name: CI
on: repository_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: github.event.action
      run: echo ${{ github.event.action }}
    - name: github.event.client_payload.test
      run: echo ${{ github.event.client_payload.test }}
